import {images} from '@assets';
import {Category, Difficulty, EnumCategory, EnumDifficulty} from '@models';

export const DifficultyConfigs: Difficulty[] = [
  {
    name: 'easy',
    row: 7,
    col: 5,
    word_count: 5,
    len_count: 6,
    type: EnumDifficulty.EASY,
  },
  {
    name: 'medium',
    row: 9,
    col: 7,
    word_count: 7,
    len_count: 8,
    type: EnumDifficulty.MEDIUM,
  },
  {
    name: 'hard',
    row: 11,
    col: 9,
    word_count: 9,
    len_count: 8,
    type: EnumDifficulty.HARD,
  },
  {
    name: 'extreme',
    row: 13,
    col: 11,
    word_count: 12,
    len_count: 10,
    type: EnumDifficulty.EXTREME,
  },
];

export const CategoryConfigs: Category[] = [
  {
    name: 'Nature',
    type: EnumCategory.NATURE,
    image: images.levels.nature,
    words: [
      'tree',
      'bird',
      'sky',
      'river',
      'cloud',
      'ocean',
      'flower',
      'mountain',
      'bee',
      'sunrise',
      'sunset',
      'rain',
      'lake',
      'wood',
      'grass',
      'bugs',
      'earth',
      'wind',
      'seed',
      'leaf',
      'rock',
      'pond',
      'hike',
      'snow',
      'sand',
      'park',
      'creek',
      'field',
      'plant',
      'fog',
      'dew',
      'trail',
      'surf',
      'dune',
      'hill',
      'shore',
      'moss',
      'bark',
      'herb',
      'river',
      'valley',
      'lagoon',
      'canyon',
      'cliff',
      'cave',
      'field',
      'peak',
      'desert',
    ],
  },
  {
    name: 'Veggie & Fruit',
    type: EnumCategory.VEGGIE_FRUIT,
    image: images.levels.fruits,
    words: [
      'carrot',
      'apple',
      'tomato',
      'orange',
      'banana',
      'potato',
      'grape',
      'peach',
      'onion',
      'kiwi',
      'mango',
      'lemon',
      'radish',
      'cherry',
      'celery',
      'melon',
      'avocado',
      'spinach',
      'pear',
      'fig',
      'beet',
      'plum',
      'lime',
      'papaya',
      'guava',
      'kale',
      'lychee',
      'cabbage',
      'date',
      'raspberry',
      'broccoli',
      'blueberry',
      'pineapple',
      'asparagus',
      'apricot',
      'tangerine',
      'zucchini',
      'paprika',
      'cranberry',
      'cauliflower',
      'blackberry',
      'watermelon',
      'eggplant',
      'artichoke',
      'radicchio',
      'gooseberry',
      'persimmon',
    ],
  },
  {
    name: 'Music',
    type: EnumCategory.MUSIC,
    image: images.levels.music,
    words: [
      'song',
      'lyric',
      'melody',
      'rhythm',
      'beat',
      'harmony',
      'tune',
      'chord',
      'note',
      'instrument',
      'guitar',
      'piano',
      'drum',
      'bass',
      'violin',
      'trumpet',
      'flute',
      'saxophone',
      'clarinet',
      'cello',
      'accordion',
      'harmonica',
      'ukulele',
      'synthesizer',
      'keyboard',
      'vocal',
      'singer',
      'artist',
      'band',
      'ensemble',
      'orchestra',
      'concert',
      'performance',
      'studio',
      'album',
      'record',
      'track',
      'playlist',
      'genre',
      'rock',
      'pop',
      'jazz',
      'blues',
      'classical',
      'rap',
      'country',
      'reggae',
      'folk',
    ],
  },
  {
    name: 'Christmas',
    type: EnumCategory.CHRISMAS,
    image: images.levels.chrismas,
    words: [
      'christmas',
      'holiday',
      'festive',
      'celebration',
      'decorations',
      'lights',
      'ornaments',
      'tree',
      'santa',
      'sleigh',
      'reindeer',
      'elves',
      'gifts',
      'presents',
      'stockings',
      'wreath',
      'mistletoe',
      'candy',
      'cookies',
      'gingerbread',
      'snow',
      'frost',
      'icicles',
      'snowman',
      'nativity',
      'angel',
      'star',
      'bells',
      'carols',
      'music',
      'jingle',
      'joy',
      'cheer',
      'family',
      'friends',
      'gatherings',
      'feast',
      'tradition',
      'spirit',
      'love',
      'warmth',
      'cozy',
      'fireplace',
      'eggnog',
      'marshmallows',
      'winter',
      'season',
      'newyear',
    ],
  },
  {
    name: 'Animals',
    type: EnumCategory.ANIMAL,
    image: images.levels.animal,
    words: [
      'dog',
      'cat',
      'pig',
      'horse',
      'cow',
      'sheep',
      'chicken',
      'duck',
      'rabbit',
      'hamster',
      'buffalo',
      'goldfish',
      'parrot',
      'turtle',
      'fish',
      'frog',
      'snake',
      'elephant',
      'giraffe',
      'monkey',
      'penguin',
      'panda',
      'koala',
      'kangaroo',
      'dolphin',
      'whale',
      'shark',
      'lion',
      'tiger',
      'bear',
      'fox',
      'wolf',
      'deer',
      'squirrel',
      'owl',
      'eagle',
      'peacock',
      'beaver',
      'seagull',
      'butterfly',
      'bee',
      'ant',
      'spider',
      'snail',
      'ladybug',
      'caterpillar',
      'dragonfly',
      'crab',
    ],
  },
  {
    name: 'Halloween',
    image: images.levels.halloween,
    type: EnumCategory.HALLOWEEN,
    words: [
      'halloween',
      'spooky',
      'scary',
      'creepy',
      'frightening',
      'costume',
      'pumpkin',
      'ghost',
      'witch',
      'wizard',
      'vampire',
      'bat',
      'skeleton',
      'zombie',
      'monster',
      'ghoul',
      'haunted',
      'candy',
      'treat',
      'candy',
      'caramel',
      'spider',
      'cobweb',
      'cat',
      'owl',
      'moon',
      'night',
      'dark',
      'graveyard',
      'tombstone',
      'scream',
      'howl',
      'shriek',
      'fog',
      'mist',
      'costume',
      'mask',
      'makeup',
      'blood',
      'sugar',
      'sweets',
      'fright',
      'skeletons',
      'witches',
      'bats',
      'haunted',
      'scarecrow',
      'cemetery',
      'boo',
    ],
  },
  {
    name: 'Emotion',
    image: images.levels.emotion,
    type: EnumCategory.EMOTION,
    words: [
      'happy',
      'sad',
      'angry',
      'excited',
      'fear',
      'surprise',
      'disgust',
      'content',
      'joy',
      'hope',
      'love',
      'hate',
      'anxiety',
      'relax',
      'bored',
      'confused',
      'curious',
      'grateful',
      'lonely',
      'energetic',
      'calm',
      'peace',
      'proud',
      'embarrass',
      'nostalgia',
      'overwhelm',
      'regret',
      'amuse',
      'bliss',
      'compassion',
      'determined',
      'envy',
      'giddy',
      'humble',
      'inspire',
      'misery',
      'optimism',
      'panic',
      'sympathy',
      'vulnerable',
      'zeal',
      'apathy',
      'devastate',
      'elation',
    ],
  },
  {
    name: 'Sport',
    image: images.levels.sport,
    type: EnumCategory.SPORT,
    words: [
      'soccer',
      'tennis',
      'golf',
      'boxing',
      'wrestling',
      'karate',
      'swimming',
      'cycling',
      'running',
      'surfing',
      'skiing',
      'cricket',
      'hockey',
      'rugby',
      'climbing',
      'rowing',
      'sailing',
      'judo',
      'fencing',
      'gymnastics',
      'badminton',
      'archery',
      'marathon',
      'hiking',
      'biking',
      'kayaking',
      'diving',
      'yoga',
      'pilates',
      'snorkeling',
      'jogging',
      'paddle',
      'bowling',
      'surf',
      'dart',
      'golfing',
      'sprint',
      'jumping',
      'skating',
      'ballet',
      'sprint',
      'fishing',
      'darts',
      'racing',
    ],
  },
  {
    name: 'Easter',
    image: images.levels.easter,
    type: EnumCategory.EASTER,
    words: [
      'easter',
      'spring',
      'jesus',
      'eggs',
      'hunt',
      'bunny',
      'lamb',
      'lily',
      'basket',
      'family',
      'feast',
      'joy',
      'peace',
      'hope',
      'reflect',
      'church',
      'sunday',
      'april',
      'friends',
      'meal',
      'dinner',
      'decorations',
      'renew',
      'celebrate',
      'faith',
      'spirit',
      'rebirth',
      'gratitude',
      'rejoice',
      'tradition',
      'festive',
      'prayer',
      'blessing',
      'savior',
      'festivity',
      'thankful',
      'worship',
      'grace',
      'love',
      'holiday',
      'chocolate',
      'faithful',
      'bless',
      'light',
      'cross',
      'hopeful',
      'rejoice',
      'parade',
      'blessings',
    ],
  },
  {
    name: 'Technology',
    image: images.levels.technology,
    type: EnumCategory.TECHNOLOGY,
    words: [
      'tech',
      'digital',
      'innovate',
      'internet',
      'compute',
      'software',
      'hardware',
      'device',
      'gadget',
      'phone',
      'tablet',
      'laptop',
      'computer',
      'network',
      'code',
      'data',
      'cyber',
      'security',
      'AI',
      'ML',
      'robotics',
      'VR',
      'AR',
      'blockchain',
      'crypto',
      'cloud',
      'IoT',
      '5g',
      'biotech',
      'nano',
      'big data',
      'analytics',
      'safety',
      'transform',
      'IT',
      'smart',
      'wearable',
      'drones',
      '3D',
      'quantum',
      'biometrics',
    ],
  },
  {
    name: 'Nation',
    image: images.levels.nation,
    type: EnumCategory.NATION,
    words: [
      'america',
      'argentina',
      'australia',
      'austria',
      'belgium',
      'brazil',
      'canada',
      'china',
      'colombia',
      'denmark',
      'egypt',
      'england',
      'finland',
      'france',
      'germany',
      'greece',
      'india',
      'indonesia',
      'iran',
      'iraq',
      'ireland',
      'israel',
      'italy',
      'japan',
      'kenya',
      'korea',
      'malaysia',
      'mexico',
      'netherlands',
      'zealand',
      'norway',
      'pakistan',
      'peru',
      'philippines',
      'poland',
      'portugal',
      'russia',
      'saudi',
      'scotland',
      'singapore',
      'africa',
      'spain',
      'sweden',
      'switzerland',
      'thailand',
      'turkey',
      'ukraine',
      'kingdom',
      'vietnam',
    ],
  },
  {
    name: 'Ocean',
    image: images.levels.ocean,
    type: EnumCategory.OCEAN,
    words: [
      'ocean',
      'marine',
      'reef',
      'coral',
      'fish',
      'shark',
      'whale',
      'dolphin',
      'seal',
      'turtle',
      'jellyfish',
      'octopus',
      'crab',
      'lobster',
      'shrimp',
      'squid',
      'starfish',
      'anemone',
      'urchin',
      'manta',
      'ray',
      'anglerfish',
      'seahorse',
      'clownfish',
      'bluefin',
      'tuna',
      'salmon',
      'herring',
      'sardine',
      'krill',
      'plankton',
      'algae',
      'seagrass',
      'kelp',
      'seaweed',
      'sponge',
      'clam',
      'oyster',
      'scallop',
      'mussel',
      'snail',
      'barnacle',
      'eel',
      'crustacean',
      'cephalopod',
      'cnidarian',
      'mollusk',
      'bivalve',
      'urchin',
    ],
  },
  {
    name: 'Bird',
    image: images.levels.bird,
    type: EnumCategory.BIRD,
    words: [
      'bird',
      'feather',
      'beak',
      'wing',
      'flight',
      'nest',
      'egg',
      'chick',
      'song',
      'call',
      'migrate',
      'perch',
      'preen',
      'plumage',
      'color',
      'species',
      'hawk',
      'eagle',
      'falcon',
      'owl',
      'sparrow',
      'robin',
      'bluebird',
      'cardinal',
      'hummingbird',
      'pigeon',
      'dove',
      'crow',
      'raven',
      'magpie',
      'swan',
      'duck',
      'goose',
      'pelican',
      'heron',
      'crane',
      'flamingo',
      'parrot',
      'macaw',
      'cockatoo',
      'toucan',
      'penguin',
      'albatross',
      'seagull',
      'swift',
      'kingfisher',
      'woodpecker',
      'warbler',
      'finch',
    ],
  },
  {
    name: 'Toy',
    image: images.levels.toy,
    type: EnumCategory.TOY,
    words: [
      'toy',
      'play',
      'fun',
      'child',
      'kid',
      'game',
      'doll',
      'action',
      'figure',
      'car',
      'truck',
      'train',
      'plane',
      'boat',
      'bike',
      'ball',
      'block',
      'puzzle',
      'building',
      'lego',
      'robot',
      'stuffed',
      'animal',
      'teddy',
      'bear',
      'puppet',
      'kite',
      'yo-yo',
      'marble',
      'top',
      'spinner',
      'model',
      'kit',
      'boardgame',
      'jigsaw',
      'telescope',
      'microscope',
      'kaleidoscope',
      'magic',
      'wand',
      'costume',
      'dress-up',
      'instrument',
      'musical',
      'playdough',
      'sandbox',
      'swing',
      'slide',
    ],
  },
  {
    name: 'House',
    image: images.levels.house,
    type: EnumCategory.HOUSE,
    words: [
      'house',
      'home',
      'room',
      'kitchen',
      'bathroom',
      'bedroom',
      'living',
      'dining',
      'closet',
      'door',
      'window',
      'wall',
      'floor',
      'ceiling',
      'roof',
      'stairs',
      'furniture',
      'couch',
      'chair',
      'table',
      'desk',
      'bed',
      'lamp',
      'shelf',
      'cabinet',
      'drawer',
      'mirror',
      'sink',
      'shower',
      'toilet',
      'tub',
      'faucet',
      'oven',
      'stove',
      'refrigerator',
      'microwave',
      'dishwasher',
      'washer',
      'dryer',
      'garage',
      'yard',
      'garden',
      'patio',
      'deck',
      'fence',
      'gate',
      'doorbell',
      'key',
      'lock',
    ],
  },
  {
    name: 'Food',
    image: images.levels.food,
    type: EnumCategory.FOOD,
    words: [
      'pizza',
      'sushi',
      'burger',
      'pasta',
      'salad',
      'tacos',
      'soup',
      'noodle',
      'curry',
      'cheese',
      'cookie',
      'cake',
      'burrito',
      'fries',
      'donut',
      'hotdog',
      'shrimp',
      'lobster',
      'sashimi',
      'ramen',
      'muffin',
      'gyro',
      'falafel',
      'rolls',
      'quiche',
      'popcorn',
      'churros',
      'waffle',
      'bagel',
      'panini',
      'cereal',
      'granola',
      'chips',
      'hummus',
      'guacamole',
      'crepe',
      'meatball',
    ],
  },
];
